### ISSUE TITLE
error for channel

### ISSUE THREAD

**Issue by changyunke** [ZhouYuxuanYX/Unsupervised-Deep-Learning-Framework-for-Anomaly-Detection-in-Time-Series-#1]
there is error during perform which program
   ext_id = self._root.findall(".//long_sequence/[@id='" + str(data_usi) + "']/values")[0].get(
IndexError: list index out of range
IndexError: Channel group 0 or Channel 3 not found

**Comment by ZhouYuxuanYX** [comment]
See the answer in issue 2
